# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repo:  # id of input
    description: 'repository to be check'
    required: true
    default: ''
  codespell_list:  # id of input
    description: 'exclude words'
    required: true
    default: 'SKIP'
  astyle_cfg:  # id of input
    description: 'Artistic Style Configuraiton file'
    required: true
    default: 'SKIP'
outputs:
  results: # id of output
    description: 'code spell results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }} 
    - ${{ inputs.codespell_list }} 
    - ${{ inputs.astyle_cfg }}
